feat(admin): generate docs according to selected factories
Disfactory/Disfactory pull request #399
Opened 2020-09-20 04:08 UTC by LittleWhiteYA

## Summary

主要做了幾件事

- document table 裡面的 code (公文號) 從 charField 改成 IntegerField
- 會根據所選的 factories 各產生一筆公文
  - code 這欄位的 format 是 YYYXXXX, 前面 3 個 Y 代表公文產生的當下是民國幾年，後面的 X 是流水號，每產生一筆公文後面的 X 數字就會 +1
  - cet_staff 會根據 factory 的 townname 找出對應的負責人

![image](https://user-images.githubusercontent.com/11289529/93693987-3b034880-fb39-11ea-8245-cb1e5f9bd658.png)

2020-09-23 12:53 UTC, noobOriented commented on backend/api/admin/actions/generate_docs.py
> +def chooseCetStaff(townname):
python 的 function name convention 是 choose_cet_staff

2020-09-23 12:55 UTC, noobOriented commented on backend/api/admin/actions/generate_docs.py
> +    format_townname = townname.replace("台", "臺")
要不要改 `normalized_townname`

2020-09-23 12:58 UTC, noobOriented commented on backend/api/admin/actions/generate_docs.py
> +        if any(county in format_townname for county in counties):
這邊是，找 format_townname 是否含有某個 county substring??
那 townname = `臺北市屌打桃園市` 會怎麼算？

2020-09-23 13:22 UTC, stegben requested changes

2020-09-23 13:22 UTC, stegben commented on backend/api/admin/actions/generate_docs.py
> +import datetime
import 順序反了，要 內建  -> 第三方 -> 自己寫的

2020-09-23 13:22 UTC, stegben commented on backend/api/admin/actions/generate_docs.py
> +        "吳沅諭": {"彰化縣", "雲林縣", "嘉義縣", "嘉義市", "臺南市", "高雄市", "屏東縣", "臺東縣", "澎湖縣", "連江縣"},
為什麼他們兩個一個比較寬，一個比較長？

2020-09-23 13:22 UTC, stegben commented on backend/api/admin/factory.py
> +from api.admin.actions import ExportCsvMixin, RestoreMixin, ExportLabelMixin, ExportDocMixin, GenerateDocsMixin
斷行吧

2020-09-23 13:22 UTC, stegben commented on backend/api/admin/factory.py
> +class FactoryAdmin(admin.ModelAdmin, ExportCsvMixin, ExportLabelMixin, ExportDocMixin, GenerateDocsMixin):
斷行吧

2020-09-23 13:22 UTC, stegben commented on backend/api/admin/factory.py
> +    actions = ["export_as_csv", "export_labels_as_docx", "export_as_docx", "generate_docs"]
斷行吧

2020-09-23 13:22 UTC, stegben commented on backend/pyproject.toml
> +flake8 = "^3.8.3"
讚

2020-09-24 14:20 UTC, LittleWhiteYA commented on backend/api/admin/actions/generate_docs.py
> +def chooseCetStaff(townname):
喔喔對XD

2020-09-24 14:21 UTC, LittleWhiteYA commented on backend/api/admin/actions/generate_docs.py
> +    format_townname = townname.replace("台", "臺")
可

2020-09-24 14:21 UTC, LittleWhiteYA commented on backend/api/admin/actions/generate_docs.py
> +        if any(county in format_townname for county in counties):
對哦   但是好像不會有這種 data XD

2020-09-24 14:21 UTC, LittleWhiteYA commented on backend/api/admin/actions/generate_docs.py
> +        "吳沅諭": {"彰化縣", "雲林縣", "嘉義縣", "嘉義市", "臺南市", "高雄市", "屏東縣", "臺東縣", "澎湖縣", "連江縣"},
這 black 幫我 format ㄉ哈哈

2020-09-24 14:21 UTC, LittleWhiteYA commented on backend/api/admin/actions/generate_docs.py
> +import datetime
乾    該用ㄍ formatter ㄌㄅ

2020-09-24 15:45 UTC, stegben commented on backend/api/admin/actions/generate_docs.py
> +        "吳沅諭": {"彰化縣", "雲林縣", "嘉義縣", "嘉義市", "臺南市", "高雄市", "屏東縣", "臺東縣", "澎湖縣", "連江縣"},
black 壞壞

2020-09-24 15:48 UTC, stegben reviewed
其餘 LGTM

2020-09-24 15:48 UTC, stegben commented on backend/api/migrations/0026_auto_20200916_1339.py
> +# Generated by Django 2.2.13 on 2020-09-16 13:39
這個檔案要重新生成了，因為 #396 先 merge 了

2020-09-27 06:09 UTC, stegben approved these changes

2020-09-27 06:09 UTC, merged