新增 Document 的 list view 與 change view
Disfactory/Disfactory pull request #408
Opened 2020-10-07 14:43 UTC by Swind

1. 新增 document admin list view 與 change view
2. 將 generate docx 的功能移到 document list view

document list
![image](https://user-images.githubusercontent.com/126123/95346308-4a7ee180-08ee-11eb-8c17-23784553fc7d.png)

document change view
![image](https://user-images.githubusercontent.com/126123/95346494-7ef29d80-08ee-11eb-90ea-75531a0fe8a1.png)

2020-10-09 11:36 UTC, stegben requested changes
Other than some coding style issue, this PR looks awesome to me

2020-10-09 11:36 UTC, stegben commented on backend/api/admin/__init__.py
> +from api.models.document import Document
Should be moved to line 8

2020-10-09 11:36 UTC, stegben commented on backend/api/admin/__init__.py
> +admin.register(Document)(DocumentAdmin)
need a last line

2020-10-09 11:36 UTC, stegben commented on backend/api/admin/document.py
> +        #'display_status_tags',
Though we know these field would be added in the future, it would be great if you add more comment beneath. Commented lines are confusing for other developer.

2020-10-09 11:36 UTC, stegben commented on backend/api/admin/document.py
> +
redundant blank line

2020-10-09 11:36 UTC, stegben commented on backend/api/admin/document.py
> +            instance.save()
This function is not used.

2020-10-12 09:12 UTC, Swind commented on backend/api/admin/document.py
> +        #'display_status_tags',
這個是我的問題，我忘記移除了 Orz
其實這個我打算放新的 pull request,  所以先註解掉。
我還是先把他移除比較好

2020-10-18 12:19 UTC, stegben approved these changes

2020-10-18 12:19 UTC, merged